#!/bin/bash
#./SRBMiner-MULTI --algorithm curvehash --pool stratum+tcp://curvehash.mine.zergpool.com:3343 --wallet D9Qg9EZCFksKgFZhnjT5ET5xc37TJXzQ9n.srbX --password c=DOGE,mc=PLSR --keepalive true
./SRBMiner-MULTI --algorithm minotaurx --pool stratum+tcp://minotaurx.mine.zergpool.com:7019 --wallet D9Qg9EZCFksKgFZhnjT5ET5xc37TJXzQ9n.srbX --password c=DOGE,mc=LCC --keepalive true
