#!/bin/bash
./SRBMiner-MULTI --algorithm cryptonight_xhv --pool stratum+tcp://mine.c3pool.com:15555 --wallet 895qPmEnyjmh7eNGtBC4FV1taT3ZiC4asDGfqjXuNbcqhzVkZ6UPqGaVTcvBpyasdRNEeSnk9CBHDGwex6fkq5p1QWQfuwS --password dockX --keepalive true
